### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by drewbuschhorn** [drewbuschhorn/account_demo#1]
Hey Adrian, invited you into my fork of your project.

Using mysqli library is a pretty good call, but you're using variable substitution in your SQL statements which opens your database to lots of nasty attacks called 'sql injection':
http://php.net/manual/en/security.database.sql-injection.php
https://en.wikipedia.org/wiki/SQL_injection

Take a look at my screencast here from your hosted instance:
http://screencast.com/t/WxmzwIvj2
by giving the last name value:

attack',email='attack@attack.com'; #

I tell the server to run the command:

update users SET last_name='attack',email='attack@attack.com'; # ' where username='x';

since the '#' tell SQL that the rest of the line is a comment, the above is considered valid SQL and run, changing _ALL_ users last_name and emails in one swoop.  Note I could change passwords as well, or any other fields.

then compare it to this one:
http://screencast.com/t/8Y3Qs7SHgRV

which is after I made this commit:
https://github.com/drewbuschhorn/account_demo/commit/725f2c554dfd783da95e55041ecd1b463f6c7dbf#diff-857ce7bc510e10e2c73cde7d31d12fbcL12

where I switched you over to 'prepared statements' on mysqli:
http://php.net/manual/en/mysqli.quickstart.prepared-statements.php

Give a hoot, eat a book and we can talk about it when you get caught up.

**Comment by drewbuschhorn** [comment]
( checkout Modern PHP Chap. 5 - Databases  https://github.com/codeguy/modern-php/tree/master/05-good-practices/databases )

**Comment by akothman** [comment]
In session.php, I have this code:

```
    $username = $_SESSION['username'];
    $conn = new mysqli('localhost','root','','demo');
    if($conn->connect_error){
            die("Connection failed: ".$conn->connect_error);
    }
    $query = "select * from users where username='$username'";
    $query_result = $conn->query($query);
```

Would I need or want to use a prepared statement in this instance, since I'm pulling the username from $_SESSION['username'], which gets its value directly from the database? My first thought would be that the input would already be okay since it's coming from the db, but not sure.

**Comment by drewbuschhorn** [comment]
Strictly speaking, you don't need to do a prepared statement in this case
for the reasons you mentioned.

However, my arguments to do it anyway would be:
1.  It builds the habit of always using prepared statements, which have
relatively little overhead.
2.  There's what are sometimes called 'second order' SQL injection attacks,
built around the idea of somehow tricking a malformed bit of data into the
DB through a vulnerable interface and then using that to hit other
endpoints.
https://en.wikipedia.org/wiki/SQL_injection#Second_Order_SQL_Injection

**Comment by drewbuschhorn** [comment]
You start to see why people use frameworks built by people smarter then
them?  I would never have thought of these attacks on my own.

**Comment by akothman** [comment]
Yeah, that's a lot to take into consideration.

Okay, after taking a while to figure out how to configure apache/mysql/php on my mac, I think I correctly switched over to prepared statements for login.php.

https://github.com/drewbuschhorn/account_demo/commit/7f820018a34995f7462f9487df44c3518545d8d0

Note to self: register.php and session.php still need to be fixed.

**Comment by akothman** [comment]
Should be resolved.

**Comment by drewbuschhorn** [comment]
Excellent, that looks like a good update!
