### ISSUE TITLE
Fix XSS issues

### ISSUE THREAD

**Issue by drewbuschhorn** [drewbuschhorn/account_demo#3]
The next most common vulnerability in web applications after SQL injection is 'Cross Site Scripting' or 'XSS'.  This attack is less severe than SQL injection in that data from the database can't be exposed, but it does allow an attacker to use your website to compromise other users accounts.

Take a look at this screencast:
http://screencast.com/t/PnsNrQUvqDrj
in it, I replace my 'Last Name' field with a snippet of javascript that alerts out my php session id.  Now imagine I somehow trick another user into viewing a page on the site which should display _my_ name to them, or that I ask an admin for the site to view my profile 'to help me out'.  When that happens, the javascript code that I've put in will run in their browser, for example, sending their session id by ajax to a receiver site I've set up.  I can then set my cookie PHPSESSION to match theirs, fake my ip if you've got the site set up really securely, and then the site will believe that I'm that user.

This one is very relevant to us, because there are parts of FA that are still vulnerable to XSS ... because it's always a judgement call between where users should be allowed to put custom javascript ( or what part of javascript ) and where it's not safe to. 
1.  When you get a chance, make a feature branch with gitflow for fixing the profile page to prevent XSS.
2.  There are two places to prevent XSS, on the input (going into the database) and on the output (coming back from the database) with largely varying schools of thought on where the issue should be fixed.  Take a look the Modern PHP Chap. 5 again.

https://en.wikipedia.org/wiki/Cross-site_scripting
https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)

**Comment by akothman** [comment]
Used htmlentities to sanitize input and output. I figured there was no harm in covering both bases? That way, if I forget one side, I have the other covered.

**Comment by drewbuschhorn** [comment]
That always sounds like a good first blush solution, but there are a few problems with using htmlentities():

http://php.net/htmlentities ( take a look at the last parameter, 'doubleencode' which is set to true, so for some text, running htmlentities on it multiple times will cause it to be more and more distorted.

Also, with a bit of carelessness, htmlentities can still allow xss:
http://php.net/manual/en/function.htmlentities.php#99896

That being said, you wouldn't be the only person in the world relying on htmlentities to protect against XSS.  However, most frameworks include or recommend something like: http://htmlpurifier.org/ to clean the data.

Have a look at this conversation:
http://stackoverflow.com/questions/11253532/html-xss-escape-on-input-vs-output
which I think comes down on escaping only on output, but reasonable people can differ on the subject.

**Comment by akothman** [comment]
Okay, cool. I like the idea of only escaping on output. From what I was reading, it seems like that's a good idea because you don't actually modify the data, and the issue is when it is rendered, not insert into the db.

I went ahead and switched over to htmlpurifier, and used composer to manage the dependency. Input isn't validated (which I can see causing some problems), but the output looks "purified" now.

**Comment by drewbuschhorn** [comment]
That looks great, good move switching over to composer, that was going to be my next suggestion.

You might also consider moving your commonly used bits of code from the top of the various files into a common file ( and then you can use that to load your common credentials file as well ).  Tradition says your want to get the autoloader loaded in the first line or two of your script, so it's available to everything else.

Back to the XSS stuff for a moment: yeah, it's a hard call to make.  I can definitely see why output sanitization won ( and that's the behavior for most php template engines these days [citation needed] ) as it makes sense to not mangle input data and in some formats it's not a threat,  but the input sanitizers have a good case that if you don't sanitize at input, you have to make sure _every_ html output of the data is escaped.  That tension is why XSS is still a big problem around, while SQL injection is more of a 'solved problem.'

**Comment by drewbuschhorn** [comment]
Oh yeah, and I consider this branch good to go.

+1 merge it!

**Comment by drewbuschhorn** [comment]
I should leave it to you close.
